version: '2'

services:

  cxxex-src-workspace:
    build:
        args:
          BUILD_TYPE: Release
        context: .
        dockerfile: Dockerfile
    image: stevenrbrandt/cxxex-src
    container_name: cxxex-src-nbk
